# Clever Cloud Database Configuration
spring.datasource.url=mysql://unvt57y5brwrzljg:WDiGWiEDcyQOVvtBfgjQ@btsyujh7rlmlkfbtqsly-mysql.services.clever-cloud.com:3306/btsyujh7rlmlkfbtqsly
spring.datasource.username=unvt57y5brwrzljg
spring.datasource.password=WDiGWiEDcyQOVvtBfgjQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true