# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# PostgreSQL DB
spring.datasource.url=jdbc:postgresql://dpg-d79umq8gjchc73fsomug-a.oregon-postgres.render.com:5432/feedbackdb_3c5j
spring.datasource.username=feedbackdb_3c5j_user
spring.datasource.password=njiH1Ibi7UabCyp2fjnvAxGjcTgpj3W8
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true